// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puckwihzpprgpgepusmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1Y2t3aWh6cHByZ3BnZXB1c216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjA2NTcsImV4cCI6MjA1NzQzNjY1N30.q4sr8i5kKQ-UhbtVb3g-jWsbna5De1leikqdP9frx_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);